"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import locale
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9ecp0l9g9@&bc+spk3xx)ox=k-d!e43ij6w&nab1x2dy3a-sr-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'core.apps.FileBrowserConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_jalali',
    'mptt',
    'tinymce',
    'taggit',
    'core.apps.CoreConfig',
    'accounts.apps.AccountsConfig',
    'products.apps.ProductsConfig',
    'homepage.apps.HomepageConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates/',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.menu_categories',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Substituting a custom User model
# https://docs.djangoproject.com/en/5.1/topics/auth/customizing/#substituting-a-custom-user-model

AUTH_USER_MODEL = 'accounts.User'


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fa'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [BASE_DIR / 'locale/',]

locale.setlocale(locale.LC_ALL, 'fa_IR.UTF-8')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static/',]

# Media files (User-uploaded files)
# https://docs.djangoproject.com/en/5.1/ref/settings/#media-url
# https://docs.djangoproject.com/en/5.1/ref/settings/#media-root

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# django-filebrowser settings
# https://django-filebrowser.readthedocs.io/en/latest/settings.html

FILEBROWSER_DIRECTORY = 'uploads/'
FILEBROWSER_MAX_UPLOAD_SIZE = 10485760 # 10 MB


# TinyMCE settings
# https://django-tinymce.readthedocs.io/en/latest/

TINYMCE_DEFAULT_CONFIG = {
    'width': "80%",
    'min_height': 400,
    'max_height': 1000,
    'menubar': False,
    'toolbar1': 'undo redo | styles | fontfamily | fontsize | lineheight | forecolor backcolor | indent outdent | removeformat | cut copy paste pastetext remove',
    'toolbar2': 'accordion charmap code codesample emoticons image link anchor numlist bullist media nonbreaking | preview | searchreplace | visualblocks visualchars | help',
    'plugins': 'accordion anchor autolink autoresize charmap code codesample directionality emoticons help image link lists advlist media nonbreaking preview quickbars searchreplace visualblocks visualchars wordcount',
    'autoresize_bottom_margin': 10,
    'image_caption': True,
    'image_advtab': True,
    'link_default_target': '_blank',
    'font_family_formats': 'Vazirmatn=vazirmatn;Andale Mono=andale mono,times; Arial=arial,helvetica,sans-serif; Arial Black=arial black,avant garde; Book Antiqua=book antiqua,palatino; Comic Sans MS=comic sans ms,sans-serif; Courier New=courier new,courier; Georgia=georgia,palatino; Helvetica=helvetica; Impact=impact,chicago; Symbol=symbol; Tahoma=tahoma,arial,helvetica,sans-serif; Terminal=terminal,monaco; Times New Roman=times new roman,times; Trebuchet MS=trebuchet ms,geneva; Verdana=verdana,geneva; Webdings=webdings; Wingdings=wingdings,zapf dingbats',
    'content_css': 'https://fonts.googleapis.com/css2?family=Vazirmatn:wght@100..900&display=swap',
    'content_style': 'body { font-family: vazirmatn; } pre[class*="language-"] { direction: ltr !important; text-align: left !important; }',}


TINYMCE_EXTRA_MEDIA = {
    'css': {
        'all': ('admin/css/tinymce-rtl-fix.css',),
    }
}

TINYMCE_FILEBROWSER = True


# Production database settings

if os.getenv('DEBUG') == 'false':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASS'),
        }
    }

# django-csp settings
# https://django-csp.readthedocs.io/en/3.8/configuration.html#policy-settings

CSP_DEFAULT_SRC = ("'unsafe-eval'",)
CSP_SCRIPT_SRC_ELEM = ("'self'",'cdn.jsdelivr.net','api.tgju.org',)
CSP_IMG_SRC = ("'self'",'static.tgju.org',)
CSP_FONT_SRC = ('data:','fonts.gstatic.com','cdn.jsdelivr.net','static.tgju.org',)
CSP_CONNECT_SRC = ("'self'",'api.tgju.org',)
CSP_STYLE_SRC = ("'unsafe-inline'",)
CSP_STYLE_SRC_ELEM = ("'self'","'unsafe-inline'",'fonts.googleapis.com','cdn.jsdelivr.net',)

if not DEBUG:
    # HTTPS/SSL Settings
    SECURE_SSL_REDIRECT = True  # Redirects all HTTP traffic to HTTPS
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # HSTS Settings (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Protect subdomains
    SECURE_HSTS_PRELOAD = True  # Allow preloading in browsers

    # Session and Cookie Settings
    SESSION_COOKIE_SECURE = True  # Cookies only sent over HTTPS
    CSRF_COOKIE_SECURE = True  # CSRF cookies only sent over HTTPS
    SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
    SESSION_COOKIE_SAMESITE = 'Lax'  # Protects against CSRF in modern browsers