# Generated by Django 5.1.4 on 2025-01-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='contact name')),
                ('tel', models.CharField(max_length=20, verbose_name='contact email')),
                ('message', models.TextField(verbose_name='contact message')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='contact ip')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
    ]
