# Generated by Django 5.1.4 on 2024-12-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='cisco', max_length=100, unique=True, verbose_name='brand slug'),
            preserve_default=False,
        ),
    ]
