# Generated by Django 5.1.4 on 2024-12-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(help_text='English letters and numbers only and no space.', max_length=100, unique=True, verbose_name='brand slug'),
        ),
    ]
