# Generated by Django 5.1.4 on 2025-01-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='promotion',
            field=models.BooleanField(default=False, help_text='Check this box to display this brand in the promotion section.', verbose_name='promotion'),
        ),
    ]
