# Generated by Django 5.1.4 on 2025-01-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_available_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='guarantee',
            field=models.CharField(default='', help_text='Determine the guarantee of this product.', max_length=100, verbose_name='product guarantee'),
            preserve_default=False,
        ),
    ]
